# Generated by Django 3.0.6 on 2022-05-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioNivel',
            fields=[
                ('cnivelcode', models.IntegerField(db_column='cNivelCode', primary_key=True, serialize=False)),
                ('sniveldesc', models.CharField(db_column='sNivelDesc', max_length=25)),
            ],
            options={
                'db_table': 'Nivel',
                'managed': False,
            },
        ),
    ]
