# Generated by Django 3.0.6 on 2022-06-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondLaboral',
            fields=[
                ('tipperccod', models.CharField(db_column='TipPerCCod', max_length=1, primary_key=True, serialize=False)),
                ('tippertdescrip', models.CharField(db_column='TipPerTDescrip', max_length=50)),
                ('tippertestad', models.CharField(db_column='TipPerTEstad', max_length=1)),
            ],
            options={
                'db_table': 'oeimTipPersonal',
                'managed': False,
            },
        ),
    ]
