# Generated by Django 3.0.6 on 2022-05-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('instccod', models.CharField(db_column='InstCCod', max_length=8, primary_key=True, serialize=False)),
                ('insttdescrip', models.CharField(blank=True, db_column='InstTDescrip', max_length=100, null=True)),
                ('insttsigla', models.CharField(blank=True, db_column='InstTSigla', max_length=16, null=True)),
                ('instctipo', models.CharField(blank=True, db_column='InstCTipo', max_length=20, null=True)),
                ('perccod', models.CharField(blank=True, db_column='PerCCod', max_length=6, null=True)),
                ('insttestad', models.CharField(blank=True, db_column='InstTEstad', max_length=1, null=True)),
                ('instncantdias', models.SmallIntegerField(blank=True, db_column='InstNcantdias', null=True)),
                ('instffechreg', models.DateTimeField(blank=True, db_column='InstFFechreg', null=True)),
                ('instffechult', models.DateTimeField(blank=True, db_column='InstFFechult', null=True)),
                ('instopera', models.CharField(blank=True, db_column='InstOpera', max_length=6, null=True)),
            ],
            options={
                'db_table': 'oeimInstitucion',
                'managed': False,
            },
        ),
    ]
