# Generated by Django 3.0.6 on 2022-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidOrg',
            fields=[
                ('uorgccod', models.CharField(db_column='UorgCCod', max_length=5, primary_key=True, serialize=False)),
                ('uorgtdescrip', models.CharField(blank=True, db_column='UorgTDescrip', max_length=100, null=True)),
                ('uorgtsigla', models.CharField(blank=True, db_column='UorgTSigla', max_length=30, null=True)),
                ('uorgctipo', models.CharField(blank=True, db_column='UorgCTipo', max_length=1, null=True)),
                ('perccod', models.CharField(blank=True, db_column='PerCCod', max_length=6, null=True)),
                ('uorgccodpat', models.CharField(blank=True, db_column='UorgCCodPat', max_length=5, null=True)),
                ('uorgccodsup', models.CharField(blank=True, db_column='UorgCCodSup', max_length=5, null=True)),
                ('uorgffechreg', models.DateTimeField(blank=True, db_column='UorgFFechreg', null=True)),
                ('uorgffechult', models.DateTimeField(blank=True, db_column='UorgFFechult', null=True)),
                ('uorgtestad', models.CharField(blank=True, db_column='UorgTEstad', max_length=1, null=True)),
                ('uorgnord', models.SmallIntegerField(blank=True, db_column='UOrgNOrd', null=True)),
                ('uorgflagst', models.CharField(blank=True, db_column='UorgFlagST', max_length=1, null=True)),
                ('uorgflagconst', models.CharField(blank=True, db_column='UorgFlagConST', max_length=1, null=True)),
            ],
            options={
                'db_table': 'oeimUnidOrg',
                'managed': False,
            },
        ),
    ]
