# Generated by Django 3.0.6 on 2022-06-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('idanexo', models.AutoField(primary_key=True, serialize=False)),
                ('num_anexo', models.CharField(max_length=45, unique=True)),
                ('direc_ip', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('marctelf', models.CharField(blank=True, max_length=45, null=True)),
                ('model', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('fechinstal', models.DateTimeField(blank=True, null=True)),
                ('fechcambio', models.DateTimeField(blank=True, null=True)),
                ('observ', models.CharField(blank=True, max_length=255, null=True)),
                ('fechreg', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anexo',
                'managed': False,
            },
        ),
    ]
