# Generated by Django 3.0.6 on 2022-05-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProceInstitucion',
            fields=[
                ('procinstccod', models.CharField(db_column='ProcInstCCod', max_length=2, primary_key=True, serialize=False)),
                ('procinsttdescrip', models.CharField(blank=True, db_column='ProcInstTDescrip', max_length=20, null=True)),
                ('procinsttestad', models.CharField(blank=True, db_column='ProcInstTestad', max_length=2, null=True)),
            ],
        ),
    ]
