# Generated by Django 3.0.6 on 2022-05-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceinstitucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceinstitucion',
            options={'managed': False},
        ),
    ]
