# Generated by Django 3.0.6 on 2022-05-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceinstitucion', '0002_auto_20220503_1600'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proceinstitucion',
            table='oeimProceInstitucion',
        ),
    ]
