# Generated by Django 3.0.6 on 2022-05-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('cestacode', models.CharField(db_column='cEstaCode', max_length=1, primary_key=True, serialize=False)),
                ('sestadesc', models.CharField(db_column='sEstaDesc', max_length=25)),
            ],
            options={
                'db_table': 'Estado_Usuario',
                'managed': False,
            },
        ),
    ]
