# Generated by Django 3.0.6 on 2022-05-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocPersonal',
            fields=[
                ('tipdocperccod', models.CharField(db_column='TIpDocPerCCod', max_length=2, primary_key=True, serialize=False)),
                ('tipdocpertdescrip', models.CharField(db_column='TIpDocPerTDescrip', max_length=50)),
                ('tipdocpernnumcaracter', models.IntegerField(blank=True, db_column='TIpDocPerNNumCaracter', null=True)),
                ('tipdocpertestad', models.CharField(db_column='TIpDocPertEstad', max_length=1)),
            ],
            options={
                'db_table': 'oeimTipDocPersonal',
                'managed': False,
            },
        ),
    ]
