# Generated by Django 3.0.6 on 2022-05-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('usrccod', models.CharField(db_column='UsrCCod', max_length=6, primary_key=True, serialize=False)),
                ('usrtlogin', models.CharField(blank=True, db_column='UsrTLogin', max_length=18, null=True)),
                ('usrtclave', models.CharField(blank=True, db_column='UsrTClave', max_length=15, null=True)),
                ('usrcindides', models.CharField(blank=True, db_column='Usrcindides', max_length=1, null=True)),
                ('usrcestacnx', models.CharField(blank=True, db_column='Usrcestacnx', max_length=1, null=True)),
                ('usrtmail', models.CharField(blank=True, db_column='UsrTMail', max_length=30, null=True)),
                ('usrtobser', models.CharField(blank=True, db_column='UsrTObser', max_length=30, null=True)),
                ('usrtindinue', models.CharField(blank=True, db_column='UsrTIndinue', max_length=1, null=True)),
                ('usrcindiadm', models.CharField(blank=True, db_column='Usrcindiadm', max_length=1, null=True)),
                ('usrvdominio', models.CharField(blank=True, db_column='UsrvDominio', max_length=80, null=True)),
                ('usrncodrol', models.SmallIntegerField(blank=True, db_column='UsrNCodRol', null=True)),
                ('usrncodpermiso', models.SmallIntegerField(blank=True, db_column='UsrNCodPermiso', null=True)),
                ('usrvcamcla', models.CharField(blank=True, db_column='Usrvcamcla', max_length=51, null=True)),
                ('usrffechexp', models.DateTimeField(blank=True, db_column='UsrFFechexp', null=True)),
                ('usrtindiest', models.CharField(blank=True, db_column='UsrTIndiest', max_length=1, null=True)),
                ('usrtesttra', models.CharField(db_column='UsrTEstTra', max_length=1)),
                ('usrtestad', models.CharField(blank=True, db_column='UsrTEstad', max_length=1, null=True)),
                ('usrcentd', models.CharField(blank=True, db_column='UsrCEntd', max_length=1, null=True)),
                ('uniorganica', models.CharField(blank=True, db_column='UniOrganica', max_length=1, null=True)),
                ('usrteexp', models.CharField(blank=True, db_column='UsrTEExp', max_length=1, null=True)),
                ('usrubigeosede', models.CharField(blank=True, db_column='UsrUbigeoSede', max_length=10, null=True)),
                ('usrnivel', models.CharField(blank=True, db_column='UsrNivel', max_length=1, null=True)),
            ],
            options={
                'db_table': 'SIUsuario',
                'managed': False,
            },
        ),
    ]
